[package]
authors = ["The Hyperledger Aries Contributors"]
edition = "2018"
exclude = [".gitignore"]
keywords = ["agents", "aries", "blockchain", "hyperledger"]
name = "arieskms"
license = "Apache-2.0"
readme = "README.md"
version = "0.1.0"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]
name = "arieskms"
path = "src/lib.rs"

[profile.release]
lto = true
opt-level = 3

[features]
default = []
storage-sqlite = ["rusqlite"]

[dependencies]
bitflags = "1.2"
failure = "0.1"
postgres = "0.17.1"
rand = { version = "0.7", optional = true }
rusqlite = { version = "0.21", optional = true, features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = { version = "1.0"}
zeroize = { version = "1.1", features = ["zeroize_derive"] }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
keychain-services = "0.1"
security-framework = "0.4"

[dev-dependencies]
